apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ibwyqp2x3-nodejs 
  janus-idp.io/tekton: ibwyqp2x3-nodejs
  backstage.io/kubernetes-id: ibwyqp2x3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ibwyqp2x3-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml